### ISSUE TITLE
DO1_2016_01_08: Ementa - Tratamento diferenciado

### ISSUE THREAD

**Issue by lcarli** [CSELATAM/PdfTextReader#43]
Tratamento específico para ementa?
Como proceder?

![image](https://user-images.githubusercontent.com/4472823/35383284-f7321726-01a8-11e8-86ab-ca44aba38fed.png)

**Comment by fcatae** [comment]
Isso é específico da publicação. Talvez o schema (issue #78) não representa muito bem as publicações?

**Comment by fcatae** [comment]
Após pensar muito nesse assunto, não será resolvido - isso será feito opcionalmente por aquele que for consumir o XML. Embora o campo de Ementa do XML fique um pouco menos preciso, o impacto é bastante baixo.
