### ISSUE TITLE
Corpo ou Titulo vieram Nulos - 65 xmls com erros na base 2012

### ISSUE THREAD

**Issue by dansemedo** [CSELATAM/PdfTextReader#57]
Article Title or Body   or Caput are null ------- File: +    C:\DOUtests\outputXml\DO1_2012_01_24\DO1_2012_01_24-artigo1.xml
--
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_01_30\DO1_2012_01_30-artigo1.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_02_01\DO1_2012_02_01-artigo360.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_02_01\DO1_2012_02_01-artigo362.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_02_03\DO1_2012_02_03-artigo37.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_02_10\DO1_2012_02_10-artigo603.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_02_13\DO1_2012_02_13-artigo138.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_02_15\DO1_2012_02_15-artigo431.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_02_16\DO1_2012_02_16-artigo650.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_02_16\DO1_2012_02_16-artigo651.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_03_02\DO1_2012_03_02-artigo487.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_03_14\DO1_2012_03_14-artigo578.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_03_23\DO1_2012_03_23-artigo491.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_03_23\DO1_2012_03_23-artigo667.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_03_23\DO1_2012_03_23-artigo677.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_03_23\DO1_2012_03_23-artigo699.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_03_23\DO1_2012_03_23-artigo717.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_03_23\DO1_2012_03_23-artigo739.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_04_18\DO1_2012_04_18-artigo465.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_04_18\DO1_2012_04_18-artigo466.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_04_18\DO1_2012_04_18-artigo469.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_04_19\DO1_2012_04_19-artigo413.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_04_19\DO1_2012_04_19-artigo415.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_04_27\DO1_2012_04_27-artigo761.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_05_03\DO1_2012_05_03-artigo328.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_05_09\DO1_2012_05_09-artigo59.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_05_14\DO1_2012_05_14-artigo338.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_05_30\DO1_2012_05_30-artigo384.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_05_30\DO1_2012_05_30-artigo608.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_05_31\DO1_2012_05_31-artigo1.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_06_06\DO1_2012_06_06-artigo404.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_06_13\DO1_2012_06_13-artigo446.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_06_14\DO1_2012_06_14-artigo416.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_06_14\DO1_2012_06_14-artigo417.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_06_14\DO1_2012_06_14-artigo418.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_06_14\DO1_2012_06_14-artigo420.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_06_14\DO1_2012_06_14-artigo425.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_06_15\DO1_2012_06_15-artigo467.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_06_15\DO1_2012_06_15-artigo479.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_06_15\DO1_2012_06_15-artigo89.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_06_22\DO1_2012_06_22-artigo54.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_06_27\DO1_2012_06_27-artigo55.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_06_28\DO1_2012_06_28-artigo155.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_07_12\DO1_2012_07_12-artigo266.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_07_19\DO1_2012_07_19-artigo53.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_07_20\DO1_2012_07_20-artigo1095.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_08_03\DO1_2012_08_03-artigo463.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_08_03\DO1_2012_08_03-artigo464.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_08_03\DO1_2012_08_03-artigo466.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_08_07\DO1_2012_08_07-artigo83.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_08_17\DO1_2012_08_17-artigo60.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_08_17\DO1_2012_08_17-artigo62.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_08_27\DO1_2012_08_27-artigo40.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_08_27\DO1_2012_08_27-artigo55.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_08_31\DO1_2012_08_31-artigo77.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_08_31\DO1_2012_08_31-artigo790.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_08_31\DO1_2012_08_31-artigo979.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_09_04\DO1_2012_09_04-artigo273.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_09_14\DO1_2012_09_14-artigo811.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_09_17\DO1_2012_09_17-artigo868.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_09_19\DO1_2012_09_19-artigo426.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_09_24\DO1_2012_09_24-artigo243.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_10_11\DO1_2012_10_11-artigo1.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_10_19\DO1_2012_10_19-artigo33.xml
Article Title or Body or Caput are null   ------- File: +    C:\DOUtests\outputXml\DO1_2012_11_23\DO1_2012_11_23-artigo607.xml

**Comment by lcarli** [comment]
@dansemedo Mesmo caso aqui. Pega 1 artigo e cola aqui para que eu possa me achar. Nem sempre a numeração do seu artigo é a mesma que a minha.

**Comment by fcatae** [comment]
Essa situação pode ser um falso positivo. 
- Title = null: ocorre somente quando a página processada começa sem título (ex: p40)
- Body = null: ocorria quando o artigo era um anexo com tabela e imagem, sem texto. Atualmente, sempre são retornadas informações.
- Caput = null: situação muito comum e normal.

Estou fechando o issue. Caso haja uma ocorrência específica, abrimos um issue para o problema com a edição do DOU e página.
