### ISSUE TITLE
DO1_2016_01_13 (p 51): Semelhança com assinatura

### ISSUE THREAD

**Issue by fcatae** [CSELATAM/PdfTextReader#59]
![image](https://user-images.githubusercontent.com/7252609/35413470-aa1ffa08-0206-11e8-96ed-d447627fee5d.png)

**Comment by lcarli** [comment]
Acho que tenho um jeito de burlar esse caso.

**Comment by fcatae** [comment]
O comportamento está correto. Por enquanto, não parece ter grande impacto se fechar.
