### ISSUE TITLE
DO1_2016_01_15 (p 39): Página não processada

### ISSUE THREAD

**Issue by fcatae** [CSELATAM/PdfTextReader#64]
![image](https://user-images.githubusercontent.com/7252609/35420818-cd69564c-0226-11e8-888a-20d44ce65a0d.png)

**Comment by lcarli** [comment]
Eu fiz pull e rodei aqui. Não consegui reproduzir o erro.

**Comment by fcatae** [comment]
![image](https://user-images.githubusercontent.com/7252609/39787868-eda17336-52fd-11e8-96a8-9aa2eed81007.png)

**Comment by fcatae** [comment]
Problema identificado: no código de extração dos Paths do PDF (PreProcessTable), os segmentos foram um retângulo. Entretanto, o Path é composto por segmentos que formam apenas segmentos paralelos e não fecham o polígono. 

Solução: Processar os SubPaths individualmente.
 
![image](https://user-images.githubusercontent.com/7252609/39823824-445e5cc6-5384-11e8-8279-801ab4cad5d5.png)

**Comment by fcatae** [comment]
Corrigido.
![image](https://user-images.githubusercontent.com/7252609/39824020-b6d4ad28-5384-11e8-9755-3496caeb0220.png)
