### ISSUE TITLE
Separar o processamento em Stages

### ISSUE THREAD

**Issue by fcatae** [CSELATAM/PdfTextReader#77]
Separar o processamento em diferentes estágios:
1) Identificação de BlockSets: algoritmo mais complexo do projeto
2) Extração de texto e segmentação: atualmente funciona bem
3) Geração de artigos XML: aqui entra muita regra de negócio com particularidades específicas do Diário Oficial e não relacionados com a "leitura de PDF"

**Comment by alexsandro-xpt** [comment]
Alguma ideia de como fazer isto?

**Comment by fcatae** [comment]
@alexsandro-xpt Sim, ainda não tive tempo de descrever o processo - preciso editar a issue para dar mais detalhes. De início é separar a identificação de BlockSet em um estágio bem definido.

**Comment by alexsandro-xpt** [comment]
Interessante, e isto não pode ser feito em paralelo, correto?

**Comment by alexsandro-xpt** [comment]
Por enquanto não, mas eu gostaria de saber o que você vai usar pra deixar expressivamente no código estes estágios?

Pois isto me parece um workflow e ou um pipeline.

Vai usar alguma lib como por exemplo o MediatR?

**Comment by fcatae** [comment]
@alexsandro-xpt  Estava pesquisando o MediatR e parece mais uma forma de abstrair a passagem de mensagens entre processos. Se for isso mesmo, acho que é demais.
Por enquanto, estou apenas separando as implementações em classes:
https://github.com/CSELATAM/PdfTextReader/tree/master/src/PdfTextReader/ParserStages

O problema é que estou praticamente reescrevendo o código atual. O algoritmo já funciona e temos resultados práticos. Mas alguns bugs não podem ser resolvidos na atual arquitetura com um pipeline único, que semelhante a esse:
https://github.com/CSELATAM/PdfTextReader/blob/master/src/PdfTextReader/ExamplesWeb.cs

**Comment by fcatae** [comment]
Processamento é realizado em estágios intermediários, que estão no namespace `ParserStages`.

```
    var stage0 = new ParserStages.StagePdfInput(context);
    stage0.Process();

    var stage1 = new ParserStages.StagePageMargins(context);
    stage1.Process();

    var stage2 = new ParserStages.StageBlocksets(context);
    stage2.Process();

    var stage3 = new ParserStages.StageRetrieveBlocks(context);
    stage3.Process();

    var stageText1 = new ParserStages.StageConvertText(context);
    stageText1.Process();

    var stageText2 = new ParserStages.StageConvertStructure(context);
    stageText2.Process();
    
    var stageContent = new ParserStages.StageConvertContent(context);
    stageContent.Process();
    
    var stageArtigos = new ParserStages.StageConvertArtigoGN(context);
    stageArtigos.Process();
```
