### ISSUE TITLE
Criar um frontend Web simples

### ISSUE THREAD

**Issue by fcatae** [CSELATAM/PdfTextReader#80]

**Comment by fcatae** [comment]
Implementado um web server como front-end. No momento, não tem recursos importantes:
- autenticação de usuário
- navegação de documentos processados
- "user experience"

Por enquanto, possui apenas a funcionalidade de Upload escondida no menu.

**Comment by fcatae** [comment]
Melhorias:
- Usar storage account
- Evitar o uso de Static Files -> Preferir um controller

**Comment by alexsandro-xpt** [comment]
Este front-end esta sendo feito em que? Alguma SPA? Razor?

**Comment by fcatae** [comment]
Começou com Razor Pages pela simplicidade e agora estou passando para o tradicional MVC (por conta de algumas funcionalidades melhores). Talvez um SPA fosse muito melhor, mas o tempo de setup é grande para nosso escopo de 1 mes. O que acha?

**Comment by alexsandro-xpt** [comment]
Talvez não seja tão grande assim não, talvez eu possa ajudar com o SPA em VueJS consultando suas APIs REST.

Se for o caso é interessante usar um Swagger pra documentar a API para que eu e outros possam guiar a respeito.

**Comment by alexsandro-xpt** [comment]
Vou me organizar pra gente conseguir isto então, lhe aviso!
