### ISSUE TITLE
Limpar exemplos de Pipeline

### ISSUE THREAD

**Issue by fcatae** [CSELATAM/PdfTextReader#86]
Pre-requisito para a tarefa de separação em estágios (#77).

Problema: Muitas dependências do Pipeline de execução dificultam futuras modificações na forma como será desacoplado.

**Comment by alexsandro-xpt** [comment]
A nível de código e arquitetura, o que você usa para gerenciar estes pipelines?

**Comment by fcatae** [comment]
É baseado em linguagem fluente, permitindo escrever o código dessa forma. Isso ajudou muito na produtividade inicial. Hoje está dando um pouco de trabalho, por isso, precisa ser revista.
```
pipeline.Input($"{inputfolder}/{basename}.pdf")
    .Output($"{outputfolder}/{basename}/parser-output.pdf")
    .AllPages<CreateTextLines>(page =>
                page.ParsePdf<PreProcessTables>()
                    .ParseBlock<IdentifyTables>()             // 1
                .ParsePdf<PreProcessImages>()
                    .ParseBlock<BasicFirstPageStats>()        // 2
                    .ParseBlock<RemoveOverlapedImages>()      // 3
                .ParsePdf<ProcessPdfText>()                   // 4
                    .ParseBlock<RemoveSmallFonts>()           // 5
                    .ParseBlock<MergeTableText>()             // 6
                    .ParseBlock<HighlightTextTable>()         // 7
                    .ParseBlock<RemoveTableText>()            // 8
                    .ParseBlock<ReplaceCharacters>()          // 9
```

O problema é que a sintaxe estava espalhada em todo o código e, por isso, torna toda modificação que impacta o Pipeline mais difícil. Nesse issue, fiz a limpeza dos códigos mais antigos para remover a dependência.
